using Airport.DAL.EF.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace Airport.DAL.EF
{
    public class AirportDbContext : IdentityDbContext<IdentityUser>
    {
        public AirportDbContext(DbContextOptions<AirportDbContext> options)
            : base(options)
        {
        }

        public DbSet<Passenger> Passengers { get; set; }
        public DbSet<Pilot> Pilots { get; set; }
        public DbSet<AircraftType> AircraftTypes { get; set; }
        public DbSet<Aircraft> Aircrafts { get; set; }
        public DbSet<PilotAircraft> PilotAircrafts { get; set; }
        public DbSet<AirportEntity> Airports { get; set; }
        public DbSet<FlightDestination> FlightDestinations { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PilotAircraft>()
                .HasKey(pa => new { pa.PilotId, pa.AircraftId });

            modelBuilder.Entity<PilotAircraft>()
                .HasOne(pa => pa.Pilot)
                .WithMany(p => p.PilotAircrafts)
                .HasForeignKey(pa => pa.PilotId);

            modelBuilder.Entity<PilotAircraft>()
                .HasOne(pa => pa.Aircraft)
                .WithMany(a => a.PilotAircrafts)
                .HasForeignKey(pa => pa.AircraftId);

            modelBuilder.Entity<FlightDestination>()
                .Property(fd => fd.TicketPrice)
                .HasPrecision(18, 2);

            //   -----------------------------  SEEDING  -----------------------------

            modelBuilder.Entity<Passenger>().HasData(
                new Passenger { Id = 1, FullName = "Kalindi Keningham", Email = "KalindiKeningham@gmail.com" },
                new Passenger { Id = 2, FullName = "Lois Leidle", Email = "LoisLeidle@gmail.com" },
                new Passenger { Id = 3, FullName = "Casi Farens", Email = "CasiFarens@gmail.com" },
                new Passenger { Id = 4, FullName = "Janna Kellert", Email = "JannaKellert@gmail.com" },
                new Passenger { Id = 5, FullName = "Conny Barnwille", Email = "ConnyBarnwille@gmail.com" },
                new Passenger { Id = 6, FullName = "Pierrette Dunmuir", Email = "PierretteDunmuir@gmail.com" },
                new Passenger { Id = 7, FullName = "Jasen Yeldham", Email = "JasenYeldham@gmail.com" },
                new Passenger { Id = 8, FullName = "Josi Hammelberg", Email = "JosiHammelberg@gmail.com" },
                new Passenger { Id = 9, FullName = "Ursulina Partner", Email = "UrsulinaPartner@gmail.com" },
                new Passenger { Id = 10, FullName = "Meris Shale", Email = "MerisShale@gmail.com" },
                new Passenger { Id = 11, FullName = "Colline Dannme", Email = "CollineDann@gmail.com" },
                new Passenger { Id = 12, FullName = "Joyann Garrettson", Email = "JoyannGarrettson@gmail.com" },
                new Passenger { Id = 13, FullName = "Shane Arorbe", Email = "ShaneArr@gmail.com" },
                new Passenger { Id = 14, FullName = "Owen Strivens", Email = "OwenStrivens@gmail.com" },
                new Passenger { Id = 15, FullName = "Moyna Bosnell", Email = "MoynaBosnell@gmail.com" },
                new Passenger { Id = 16, FullName = "Henrik Sivyer", Email = "Henrik@gmail.com" },
                new Passenger { Id = 17, FullName = "Cullan Dogerty", Email = "Cullan@gmail.com" },
                new Passenger { Id = 18, FullName = "Jens Aitken", Email = "Aitken@gmail.com" },
                new Passenger { Id = 19, FullName = "Lorilee Kryszkiecicz", Email = "Kryszkiecicz@gmail.com" },
                new Passenger { Id = 20, FullName = "Myrta Soggete", Email = "Myrta@gmail.com" },
                new Passenger { Id = 21, FullName = "Craig Backeren", Email = "Craig@gmail.com" },
                new Passenger { Id = 22, FullName = "Jacquelynn Plackstone", Email = "Plackstone@gmail.com" },
                new Passenger { Id = 23, FullName = "Therese Gerwood", Email = "Gerwood@gmail.com" },
                new Passenger { Id = 24, FullName = "Jefferson Montacute", Email = "Montacute@gmail.com" },
                new Passenger { Id = 25, FullName = "Jameson Elgarerson", Email = "Elgar@gmail.com" },
                new Passenger { Id = 26, FullName = "Gilberte Shalders", Email = "Shalders@gmail.com" },
                new Passenger { Id = 27, FullName = "Siegfried Simony", Email = "Simony@gmail.com" },
                new Passenger { Id = 28, FullName = "Kimball Deemond", Email = "Deem@gmail.com" },
                new Passenger { Id = 29, FullName = "Sascha Ruddom", Email = "Ruddom@gmail.com" },
                new Passenger { Id = 30, FullName = "Janelle Southern", Email = "Janelle Southern@gmail.com" },
                new Passenger { Id = 31, FullName = "Chaunce Taffe", Email = "ChaunceTaffe@gmail.com" },
                new Passenger { Id = 32, FullName = "Dante Sagerson", Email = "DanteSagerson@gmail.com" },
                new Passenger { Id = 33, FullName = "Carey Flannery", Email = "CareyFlannery@gmail.com" },
                new Passenger { Id = 34, FullName = "Lizzie Iscowitz", Email = "LizzieIscowitz@gmail.com" },
                new Passenger { Id = 35, FullName = "Zeke Rowston", Email = "ZekeRowston@gmail.com" },
                new Passenger { Id = 36, FullName = "Adelle Kurten", Email = "AdelleKurten@gmail.com" },
                new Passenger { Id = 37, FullName = "Rolland Trevna", Email = "RollandTrevna@gmail.com" },
                new Passenger { Id = 38, FullName = "Gwynne Bleakley", Email = "GwynneBleakley@gmail.com" },
                new Passenger { Id = 39, FullName = "Darby Rothert", Email = "DarbyRothert@gmail.com" },
                new Passenger { Id = 40, FullName = "Meridel Straker", Email = "MeridelStraker@gmail.com" },
                new Passenger { Id = 41, FullName = "Raynor Dobbison", Email = "RaynorDobbison@gmail.com" },
                new Passenger { Id = 42, FullName = "Burnaby Blackater", Email = "BurnabyBlackater@gmail.com" },
                new Passenger { Id = 43, FullName = "Yulin Moseby", Email = "YulMoseby@gmail.com" },
                new Passenger { Id = 44, FullName = "Miles Scruby", Email = "MilesScruby@gmail.com" },
                new Passenger { Id = 45, FullName = "Jeanine Gerren", Email = "JeanineGerren@gmail.com" },
                new Passenger { Id = 46, FullName = "Carmel Lendrem", Email = "CarmelLendrem@gmail.com" },
                new Passenger { Id = 47, FullName = "Allsun O' Kelleher", Email = "AllsunKelleher@gmail.com" },
                new Passenger { Id = 48, FullName = "Lanita Crockatt", Email = "LanitaCrockatt@gmail.com" },
                new Passenger { Id = 49, FullName = "Georges Lanston", Email = "GeorgesLanston@gmail.com" },
                new Passenger { Id = 50, FullName = "Abbey Pedrinson", Email = "AbbeyPedri@gmail.com" },
                new Passenger { Id = 51, FullName = "Micheal Newtown", Email = "MichealNewtown@gmail.com" },
                new Passenger { Id = 52, FullName = "Sari Chicotti", Email = "SariChicotti@gmail.com" },
                new Passenger { Id = 53, FullName = "Gibbie Liggens", Email = "GibbieLiggens@gmail.com" },
                new Passenger { Id = 54, FullName = "Odele Sinncock", Email = "OdeleSinncock@gmail.com1" },
                new Passenger { Id = 55, FullName = "Tisha Paterson", Email = "TishaPatey@gmail.com" },
                new Passenger { Id = 56, FullName = "Mariele Drinkhall", Email = "MarieleDrinkhall@gmail.com" },
                new Passenger { Id = 57, FullName = "Raymund Clacenson", Email = "RaymundClace@gmail.com" },
                new Passenger { Id = 58, FullName = "Joshuah Duckers", Email = "JoshuahDuckers@gmail.com" },
                new Passenger { Id = 59, FullName = "Kelcy Viccary", Email = "KelcyViccary@gmail.com" },
                new Passenger { Id = 60, FullName = "Kaylee Ponten", Email = "KayleePonten@gmail.com" },
                new Passenger { Id = 61, FullName = "Mady Viccary", Email = "MadyViccary@gmail.com" },
                new Passenger { Id = 62, FullName = "Mattie Hampton", Email = "MattieHampton@gmail.com" },
                new Passenger { Id = 63, FullName = "Kaylee Coushe", Email = "KayleeCoushe@gmail.com" },
                new Passenger { Id = 64, FullName = "Lucita Robelet", Email = "LucitaRobelet@gmail.com" },
                new Passenger { Id = 65, FullName = "Findley Iacoboni", Email = "FindleyIacoboni@gmail.com" },
                new Passenger { Id = 66, FullName = "Allan Wedge", Email = "AllanWedge@gmail.com" },
                new Passenger { Id = 67, FullName = "Cordey Tremblet", Email = "CordeyTremblet@gmail.com" },
                new Passenger { Id = 68, FullName = "Gaye Sillars", Email = "GayeSillars@gmail.com" },
                new Passenger { Id = 69, FullName = "Pieter Curphey", Email = "PieterCurphey@gmail.com" },
                new Passenger { Id = 70, FullName = "Ewen MacDearmont", Email = "Ewen-MacDearmont@gmail.com" },
                new Passenger { Id = 71, FullName = "Mignon Pennell", Email = "ignonPennell@gmail.com" },
                new Passenger { Id = 72, FullName = "Alano Georgot", Email = "AlanoGeorgot@gmail.com" },
                new Passenger { Id = 73, FullName = "Alley Couch", Email = "Alleyouch@gmail.com" },
                new Passenger { Id = 74, FullName = "Liam Offner", Email = "LiamOffner@gmail.com" },
                new Passenger { Id = 75, FullName = "Elbertina Kleinsinger", Email = "ElbertinaKleinsinger@gmail.com" },
                new Passenger { Id = 76, FullName = "Elbtina Klsinger", Email = "ElbtinaKlsinger@gmail.com" },
                new Passenger { Id = 77, FullName = "Norean Sharpless", Email = "NoreanSharpless@gmail.com" },
                new Passenger { Id = 78, FullName = "Vincents Bould", Email = "VincentsBould@gmail.com" },
                new Passenger { Id = 79, FullName = "Parker McGeorge", Email = "ParkerMcGeorge@gmail.com" },
                new Passenger { Id = 80, FullName = "Gregorius May", Email = "GregoriusMay@gmail.com" },
                new Passenger { Id = 81, FullName = "Bev Wrigglesworth", Email = "BevWrigglesworth@gmail.com" },
                new Passenger { Id = 82, FullName = "Courtney Gawkes", Email = "CourtneyGawkes@gmail.com" },
                new Passenger { Id = 83, FullName = "Courtney Matiasek", Email = "CourtneyMatiasek@gmail.com" },
                new Passenger { Id = 84, FullName = "Corine Gunda", Email = "CoriGunda@gmail.com" },
                new Passenger { Id = 85, FullName = "Mandy Scoggin", Email = "MandyScoggin@gmail.com" },
                new Passenger { Id = 86, FullName = "Juane Gorrynsen", Email = "JuanGorry@gmail.com" },
                new Passenger { Id = 87, FullName = "Randie Cridgeno", Email = "RandieCridge@gmail.com" },
                new Passenger { Id = 88, FullName = "Courtnay Devoy", Email = "CourtnayDevoy@gmail.com" },
                new Passenger { Id = 89, FullName = "Haven Seaton", Email = "HavenSeaton@gmail.com" },
                new Passenger { Id = 90, FullName = "Nicolai Seaborn", Email = "NicolaiSeaborn@gmail.com" },
                new Passenger { Id = 91, FullName = "Mona Crose", Email = "MonaCrose@gmail.com" },
                new Passenger { Id = 92, FullName = "Alyson Jankowski", Email = "AlysonJankowski@gmail.com" },
                new Passenger { Id = 93, FullName = "Jeralee Tue", Email = "JeraleeTue@gmail.com" },
                new Passenger { Id = 94, FullName = "Lonny Carnachen", Email = "LonnyCarnachen@gmail.com" },
                new Passenger { Id = 95, FullName = "Kora Nichol", Email = "KoraNichol@gmail.com" },
                new Passenger { Id = 96, FullName = "Kermy Bertot", Email = "KermyBertot@gmail.com" },
                new Passenger { Id = 97, FullName = "Stanislaus Baggallay", Email = "StanislausBaggallay@gmail.com" },
                new Passenger { Id = 98, FullName = "Danny Simoneau", Email = "DannySimoneau@gmail.com" },
                new Passenger { Id = 99, FullName = "Rubin Meaddowcroft", Email = "RubinMeaddowcroft@gmail.com" },
                new Passenger { Id = 100, FullName = "Marsha Cridge", Email = "MarshaCridge@gmail.com" },
                new Passenger { Id = 101, FullName = "Elysha Maydwell", Email = "ElyshaMaydwell@gmail.com" },
                new Passenger { Id = 102, FullName = "Cridge1232", Email = "Cridge123@gmail.com" },
                new Passenger { Id = 103, FullName = "Marsha2345", Email = "MarshaC3456@gmail.com" },
                new Passenger { Id = 104, FullName = "Marde123", Email = "Mardge123@gmail.com" },
                new Passenger { Id = 105, FullName = "CdSe232", Email = "CridgeSe232@gmail.com" },
                new Passenger { Id = 106, FullName = "Axaner23", Email = "Alexander23@gmail.com" },
                new Passenger { Id = 107, FullName = "Janka23", Email = "Janka123@gmail.com" },
                new Passenger { Id = 108, FullName = "S", Email = "Saxon34@gmail.com" },
                new Passenger { Id = 109, FullName = "Lob", Email = "Lob@gmail.com" },
                new Passenger { Id = 110, FullName = "Ge", Email = "Ge@gmail.com" }
            );

            modelBuilder.Entity<Pilot>().HasData(
                new Pilot { Id = 1, FirstName = "Alexander", LastName = "Jubb", Age = 40, Rating = 3.3 },
                new Pilot { Id = 2, FirstName = "Cullan", LastName = "Geram", Age = 54, Rating = 1.5 },
                new Pilot { Id = 3, FirstName = "Germana", LastName = "Emburey", Age = 38, Rating = 9.2 },
                new Pilot { Id = 4, FirstName = "Janka", LastName = "Loblie", Age = 48, Rating = 7.5 },
                new Pilot { Id = 5, FirstName = "Krystal", LastName = "Cuckson", Age = 54, Rating = 9.0 },
                new Pilot { Id = 6, FirstName = "Susy", LastName = "Borrel", Age = 42, Rating = 3.7 },
                new Pilot { Id = 7, FirstName = "Saxon", LastName = "Veldman", Age = 43, Rating = 3.2 },
                new Pilot { Id = 8, FirstName = "Lenore", LastName = "Romera", Age = 29, Rating = 6.9 },
                new Pilot { Id = 9, FirstName = "Enrichetta", LastName = "Jeremiah", Age = 60, Rating = 4.4 },
                new Pilot { Id = 10, FirstName = "Delaney", LastName = "Stove", Age = 24, Rating = 6.9 },
                new Pilot { Id = 11, FirstName = "Ilaire", LastName = "Tomaszewicz", Age = 25, Rating = 7.8 },
                new Pilot { Id = 12, FirstName = "Genna", LastName = "Jaquet", Age = 36, Rating = 4.0 },
                new Pilot { Id = 13, FirstName = "Carlotta", LastName = "Dykas", Age = 34, Rating = 6.4 },
                new Pilot { Id = 14, FirstName = "Viki", LastName = "Oneal", Age = 57, Rating = 4.9 },
                new Pilot { Id = 15, FirstName = "Anthe", LastName = "Larne", Age = 43, Rating = 7.1 },
                new Pilot { Id = 16, FirstName = "Philip", LastName = "Penwarden", Age = 45, Rating = 3.7 },
                new Pilot { Id = 17, FirstName = "Cristi", LastName = "Ravenshear", Age = 38, Rating = 1.4 },
                new Pilot { Id = 18, FirstName = "Louie", LastName = "Vogel", Age = 44, Rating = 7.4 },
                new Pilot { Id = 19, FirstName = "Roddie", LastName = "Gribben", Age = 30, Rating = 8.0 },
                new Pilot { Id = 20, FirstName = "Boyce", LastName = "Briddock", Age = 45, Rating = 6.7 },
                new Pilot { Id = 21, FirstName = "Heidie", LastName = "Blacksell", Age = 29, Rating = 3.1 },
                new Pilot { Id = 22, FirstName = "Lexie", LastName = "Salasar", Age = 22, Rating = 9.5 },
                new Pilot { Id = 23, FirstName = "Harmony", LastName = "Beincken", Age = 46, Rating = 2.2 },
                new Pilot { Id = 24, FirstName = "Dick", LastName = "Eton", Age = 42, Rating = 8.8 },
                new Pilot { Id = 25, FirstName = "Philis", LastName = "Treswell", Age = 54, Rating = 6.8 },
                new Pilot { Id = 26, FirstName = "Crosby", LastName = "Godlee", Age = 55, Rating = 9.6 },
                new Pilot { Id = 27, FirstName = "Gerhard", LastName = "Alderson", Age = 44, Rating = 7.2 },
                new Pilot { Id = 28, FirstName = "Dominga", LastName = "Cavy", Age = 24, Rating = 3.6 },
                new Pilot { Id = 29, FirstName = "Judye", LastName = "Albrooke", Age = 28, Rating = 3.1 },
                new Pilot { Id = 30, FirstName = "Felice", LastName = "Bartol", Age = 47, Rating = 2.1 },
                new Pilot { Id = 31, FirstName = "Adolpho", LastName = "Wainscot", Age = 36, Rating = 4.7 },
                new Pilot { Id = 32, FirstName = "Aurilia", LastName = "McCready", Age = 49, Rating = 1.4 },
                new Pilot { Id = 33, FirstName = "Neill", LastName = "Woof", Age = 37, Rating = 8.5 },
                new Pilot { Id = 34, FirstName = "Rab", LastName = "McDarmid", Age = 60, Rating = 2.4 },
                new Pilot { Id = 35, FirstName = "Ardith", LastName = "Kienlein", Age = 46, Rating = 9.7 },
                new Pilot { Id = 36, FirstName = "Berenice", LastName = "Liddiatt", Age = 56, Rating = 1.6 },
                new Pilot { Id = 37, FirstName = "Ailina", LastName = "Sebyer", Age = 59, Rating = 8.7 },
                new Pilot { Id = 38, FirstName = "Jaynell", LastName = "Kidson", Age = 22, Rating = 6.2 },
                new Pilot { Id = 39, FirstName = "Carina", LastName = "Vanyatin", Age = 38, Rating = 4.3 },
                new Pilot { Id = 40, FirstName = "Edna", LastName = "Heatley", Age = 57, Rating = 7.5 },
                new Pilot { Id = 41, FirstName = "Hally", LastName = "Barthelmes", Age = 46, Rating = 8.9 },
                new Pilot { Id = 42, FirstName = "Leanna", LastName = "Olensby", Age = 40, Rating = 4.8 },
                new Pilot { Id = 43, FirstName = "Dell", LastName = "Willoughey", Age = 23, Rating = 6.3 },
                new Pilot { Id = 44, FirstName = "Guinevere", LastName = "Gras", Age = 33, Rating = 6.3 },
                new Pilot { Id = 45, FirstName = "Jerrie", LastName = "Myles", Age = 21, Rating = 1.8 },
                new Pilot { Id = 46, FirstName = "Francoise", LastName = "Cusack", Age = 52, Rating = 1.1 },
                new Pilot { Id = 47, FirstName = "Happy", LastName = "Bezant", Age = 41, Rating = 8.3 },
                new Pilot { Id = 48, FirstName = "Kingsly", LastName = "Ianiello", Age = 58, Rating = 7.1 },
                new Pilot { Id = 49, FirstName = "Leonhard", LastName = "Tukely", Age = 28, Rating = 5.1 },
                new Pilot { Id = 50, FirstName = "Joe", LastName = "Waine", Age = 21, Rating = 4.4 }
            );

            modelBuilder.Entity<AircraftType>().HasData(
                new AircraftType { Id = 1, TypeName = "Jumbo Passenger Jets" },
                new AircraftType { Id = 2, TypeName = "Mid-Size Passenger Jets" },
                new AircraftType { Id = 3, TypeName = "Light Passenger Jets" },
                new AircraftType { Id = 4, TypeName = "Passenger Turboprops" },
                new AircraftType { Id = 5, TypeName = "Cargo Airplanes" },
                new AircraftType { Id = 6, TypeName = "VLJ (Very Light Jets)" },
                new AircraftType { Id = 7, TypeName = "Light Business Jets" },
                new AircraftType { Id = 8, TypeName = "Mid-Size Business Jets" },
                new AircraftType { Id = 9, TypeName = "Heavy Business Jets" },
                new AircraftType { Id = 10, TypeName = "Military Jets" },
                new AircraftType { Id = 11, TypeName = "Private Single Engine" },
                new AircraftType { Id = 12, TypeName = "Twin Turboprops" },
                new AircraftType { Id = 13, TypeName = "Aerobatic" },
                new AircraftType { Id = 14, TypeName = "Amphibious" },
                new AircraftType { Id = 15, TypeName = "Military Turboprops" }
            );

            modelBuilder.Entity<Aircraft>().HasData(
                new Aircraft { Id = 1, Manufacturer = "Safran", Model = "LEAP-1A", Year = 2021, FlightHours = 559, Condition = "A", AircraftTypeId = 3 },
                new Aircraft { Id = 2, Manufacturer = "Safran", Model = "LEAP-1B", Year = 2012, FlightHours = 275, Condition = "A", AircraftTypeId = 4 },
                new Aircraft { Id = 3, Manufacturer = "Safran", Model = "LEAP-1C", Year = 2004, FlightHours = 0, Condition = "B", AircraftTypeId = 1 },
                new Aircraft { Id = 4, Manufacturer = "Safran", Model = "CFM56", Year = 2020, FlightHours = 703, Condition = "C", AircraftTypeId = 1 },
                new Aircraft { Id = 5, Manufacturer = "Safran", Model = "SaM146", Year = 2016, FlightHours = 303, Condition = "B", AircraftTypeId = 4 },
                new Aircraft { Id = 6, Manufacturer = "Safran", Model = "TP400", Year = 2006, FlightHours = 636, Condition = "B", AircraftTypeId = 5 },
                new Aircraft { Id = 7, Manufacturer = "Safran", Model = "M88", Year = 2001, FlightHours = 695, Condition = "C", AircraftTypeId = 2 },
                new Aircraft { Id = 8, Manufacturer = "Safran", Model = "SaM14612", Year = 2015, FlightHours = 527, Condition = "C", AircraftTypeId = 2 },
                new Aircraft { Id = 9, Manufacturer = "Safran", Model = "LEAP-1D", Year = 2013, FlightHours = 835, Condition = "B", AircraftTypeId = 2 },
                new Aircraft { Id = 10, Manufacturer = "Safran", Model = "LEAP-1H", Year = 2002, FlightHours = 639, Condition = "C", AircraftTypeId = 1 },
                new Aircraft { Id = 11, Manufacturer = "Safran", Model = "LEAP-1H", Year = 2019, FlightHours = 885, Condition = "A", AircraftTypeId = 8 },
                new Aircraft { Id = 12, Manufacturer = "Safran", Model = "LEAP-1J", Year = 2008, FlightHours = 357, Condition = "C", AircraftTypeId = 9 },
                new Aircraft { Id = 13, Manufacturer = "Safran", Model = "TP500", Year = 2007, FlightHours = 849, Condition = "B", AircraftTypeId = 10 },
                new Aircraft { Id = 14, Manufacturer = "Safran", Model = "TP600", Year = 2020, FlightHours = 98, Condition = "B", AircraftTypeId = 11 },
                new Aircraft { Id = 15, Manufacturer = "Northrop Grumman", Model = "EA-6 Prowler", Year = 2021, FlightHours = 334, Condition = "B", AircraftTypeId = 12 },
                new Aircraft { Id = 16, Manufacturer = "Northrop Grumman", Model = "E-2 Hawkeye", Year = 2007, FlightHours = 617, Condition = "C", AircraftTypeId = 13 },
                new Aircraft { Id = 17, Manufacturer = "Northrop Grumman", Model = "C-2 Greyhound", Year = 2019, FlightHours = 720, Condition = "A", AircraftTypeId = 14 },
                new Aircraft { Id = 18, Manufacturer = "Northrop Grumman", Model = "Model 151 (ARES)", Year = 2004, FlightHours = 0, Condition = "A", AircraftTypeId = 15 },
                new Aircraft { Id = 19, Manufacturer = "Northrop Grumman", Model = "Douglas YF-23 ", Year = 2015, FlightHours = 64, Condition = "B", AircraftTypeId = 1 },
                new Aircraft { Id = 20, Manufacturer = "Northrop Grumman", Model = "E-8 Joint STARS", Year = 2015, FlightHours = 480, Condition = "C", AircraftTypeId = 2 },
                new Aircraft { Id = 21, Manufacturer = "Northrop Grumman", Model = "TRW RQ-5 Hunter", Year = 2010, FlightHours = 620, Condition = "A", AircraftTypeId = 3 },
                new Aircraft { Id = 22, Manufacturer = "Northrop Grumman", Model = "B-2 Spirit", Year = 2002, FlightHours = 796, Condition = "B", AircraftTypeId = 4 },
                new Aircraft { Id = 23, Manufacturer = "Northrop Grumman", Model = "X-47A Pegasus", Year = 2020, FlightHours = 906, Condition = "B", AircraftTypeId = 5 },
                new Aircraft { Id = 24, Manufacturer = "Northrop Grumman", Model = "Bat", Year = 2008, FlightHours = 149039, Condition = "C", AircraftTypeId = 6 },
                new Aircraft { Id = 25, Manufacturer = "Northrop Grumman", Model = "KC-45 (KC-30)", Year = 2002, FlightHours = 414, Condition = "A", AircraftTypeId = 7 },
                new Aircraft { Id = 26, Manufacturer = "Northrop Grumman", Model = "Sandstorm", Year = 2002, FlightHours = 342, Condition = "C", AircraftTypeId = 8 },
                new Aircraft { Id = 27, Manufacturer = "Northrop Grumman", Model = "DARPA KQ-X", Year = 2010, FlightHours = 894, Condition = "C", AircraftTypeId = 9 },
                new Aircraft { Id = 28, Manufacturer = "GE Aviation", Model = "GE90", Year = 2013, FlightHours = 380, Condition = "C", AircraftTypeId = 10 },
                new Aircraft { Id = 29, Manufacturer = "GE Aviation", Model = "GE9X", Year = 2011, FlightHours = 148, Condition = "A", AircraftTypeId = 11 },
                new Aircraft { Id = 30, Manufacturer = "GE Aviation", Model = "GEnx", Year = 2007, FlightHours = 65, Condition = "A", AircraftTypeId = 12 },
                new Aircraft { Id = 31, Manufacturer = "GE Aviation", Model = "GP7200c", Year = 2007, FlightHours = 395, Condition = "B", AircraftTypeId = 13 },
                new Aircraft { Id = 32, Manufacturer = "GE Aviation", Model = "CF6", Year = 2000, FlightHours = 936, Condition = "C", AircraftTypeId = 14 },
                new Aircraft { Id = 33, Manufacturer = "GE Aviation", Model = "CFM56", Year = 2008, FlightHours = 128, Condition = "A", AircraftTypeId = 15 },
                new Aircraft { Id = 34, Manufacturer = "GE Aviation", Model = "LEAP", Year = 2004, FlightHours = 847, Condition = "C", AircraftTypeId = 6 },
                new Aircraft { Id = 35, Manufacturer = "GE Aviation", Model = "CF34", Year = 2011, FlightHours = 18, Condition = "A", AircraftTypeId = 7 },
                new Aircraft { Id = 36, Manufacturer = "GE Aviation", Model = "CT7", Year = 2005, FlightHours = 96, Condition = "B", AircraftTypeId = 8 },
                new Aircraft { Id = 37, Manufacturer = "GE Aviation", Model = "CT8", Year = 2020, FlightHours = 4, Condition = "B", AircraftTypeId = 9 },
                new Aircraft { Id = 38, Manufacturer = "GE Aviation", Model = "CT9", Year = 2020, FlightHours = 112, Condition = "C", AircraftTypeId = 10 },
                new Aircraft { Id = 39, Manufacturer = "GE Aviation", Model = "CT10", Year = 2002, FlightHours = 275, Condition = "A", AircraftTypeId = 11 },
                new Aircraft { Id = 40, Manufacturer = "GE Aviation", Model = "CF67", Year = 2007, FlightHours = 582, Condition = "B", AircraftTypeId = 14 },
                new Aircraft { Id = 41, Manufacturer = "GE Aviation", Model = "CF8", Year = 2001, FlightHours = 508, Condition = "A", AircraftTypeId = 11 },
                new Aircraft { Id = 42, Manufacturer = "GE Aviation", Model = "CF9", Year = 2004, FlightHours = 574, Condition = "B", AircraftTypeId = 15 },
                new Aircraft { Id = 43, Manufacturer = "GE Aviation", Model = "CF10", Year = 2003, FlightHours = 499, Condition = "A", AircraftTypeId = 12 },
                new Aircraft { Id = 44, Manufacturer = "Boeing", Model = "787", Year = 2004, FlightHours = 623, Condition = "C", AircraftTypeId = 11 },
                new Aircraft { Id = 45, Manufacturer = "Boeing", Model = "787", Year = 2007, FlightHours = 0, Condition = "C", AircraftTypeId = 13 },
                new Aircraft { Id = 46, Manufacturer = "Boeing", Model = "787", Year = 2019, FlightHours = 386, Condition = "B", AircraftTypeId = 11 },
                new Aircraft { Id = 47, Manufacturer = "Boeing", Model = "787", Year = 2009, FlightHours = 849, Condition = "A", AircraftTypeId = 12 },
                new Aircraft { Id = 48, Manufacturer = "Boeing", Model = "787", Year = 2021, FlightHours = 0, Condition = "B", AircraftTypeId = 13 },
                new Aircraft { Id = 49, Manufacturer = "Boeing", Model = "787", Year = 2010, FlightHours = 382, Condition = "B", AircraftTypeId = 12 },
                new Aircraft { Id = 50, Manufacturer = "Boeing", Model = "787", Year = 2011, FlightHours = 440, Condition = "A", AircraftTypeId = 13 },
                new Aircraft { Id = 51, Manufacturer = "Boeing", Model = "787", Year = 2013, FlightHours = 414, Condition = "B", AircraftTypeId = 7 },
                new Aircraft { Id = 52, Manufacturer = "Boeing", Model = "787", Year = 2012, FlightHours = 591, Condition = "B", AircraftTypeId = 8 },
                new Aircraft { Id = 53, Manufacturer = "Boeing", Model = "787", Year = 2007, FlightHours = 0, Condition = "C", AircraftTypeId = 9 },
                new Aircraft { Id = 54, Manufacturer = "Boeing", Model = "787", Year = 2013, FlightHours = 118, Condition = "C", AircraftTypeId = 10 },
                new Aircraft { Id = 55, Manufacturer = "Boeing", Model = "747", Year = 2012, FlightHours = 246, Condition = "A", AircraftTypeId = 7 },
                new Aircraft { Id = 56, Manufacturer = "Boeing", Model = "747", Year = 2010, FlightHours = 147, Condition = "B", AircraftTypeId = 8 },
                new Aircraft { Id = 57, Manufacturer = "Boeing", Model = "747", Year = 2019, FlightHours = 189, Condition = "A", AircraftTypeId = 9 },
                new Aircraft { Id = 58, Manufacturer = "Boeing", Model = "BBJ", Year = 2001, FlightHours = 349, Condition = "B", AircraftTypeId = 10 },
                new Aircraft { Id = 59, Manufacturer = "Boeing", Model = "BBJ", Year = 2013, FlightHours = 925, Condition = "C", AircraftTypeId = 1 },
                new Aircraft { Id = 60, Manufacturer = "Boeing", Model = "BBJ", Year = 2007, FlightHours = 860, Condition = "C", AircraftTypeId = 12 },
                new Aircraft { Id = 61, Manufacturer = "Boeing", Model = "737", Year = 2005, FlightHours = 131, Condition = "B", AircraftTypeId = 13 },
                new Aircraft { Id = 62, Manufacturer = "Boeing", Model = "737", Year = 2002, FlightHours = 870, Condition = "C", AircraftTypeId = 14 },
                new Aircraft { Id = 63, Manufacturer = "Boeing", Model = "737", Year = 2020, FlightHours = 599, Condition = "C", AircraftTypeId = 15 },
                new Aircraft { Id = 64, Manufacturer = "Boeing", Model = "737", Year = 2010, FlightHours = 824, Condition = "A", AircraftTypeId = 2 },
                new Aircraft { Id = 65, Manufacturer = "Rolls-Royce Holdings", Model = "Trent XWB", Year = 2005, FlightHours = 775, Condition = "A", AircraftTypeId = 1 },
                new Aircraft { Id = 66, Manufacturer = "Rolls-Royce Holdings", Model = "Trent 900", Year = 2005, FlightHours = 958, Condition = "B", AircraftTypeId = 4 },
                new Aircraft { Id = 67, Manufacturer = "Rolls-Royce Holdings", Model = "EJ200", Year = 2003, FlightHours = 100, Condition = "C", AircraftTypeId = 4 },
                new Aircraft { Id = 68, Manufacturer = "Rolls-Royce Holdings", Model = "Eurofighter Typhoon", Year = 2001, FlightHours = 256, Condition = "C", AircraftTypeId = 2 },
                new Aircraft { Id = 69, Manufacturer = "Rolls-Royce Holdings", Model = "Trent 700", Year = 2006, FlightHours = 776, Condition = "C", AircraftTypeId = 1 },
                new Aircraft { Id = 70, Manufacturer = "Rolls-Royce Holdings", Model = "Trent 500", Year = 2010, FlightHours = 225, Condition = "C", AircraftTypeId = 5 },
                new Aircraft { Id = 71, Manufacturer = "Lockheed Martin", Model = "P-38 Lightning", Year = 2011, FlightHours = 571, Condition = "B", AircraftTypeId = 6 },
                new Aircraft { Id = 72, Manufacturer = "Lockheed Martin", Model = "P-80 Shooting Star", Year = 2002, FlightHours = 557, Condition = "B", AircraftTypeId = 7 },
                new Aircraft { Id = 73, Manufacturer = "Lockheed Martin", Model = "F-94 Starfire", Year = 2018, FlightHours = 839, Condition = "A", AircraftTypeId = 8 },
                new Aircraft { Id = 74, Manufacturer = "Lockheed Martin", Model = "F-104 Starfighter", Year = 2008, FlightHours = 805, Condition = "C", AircraftTypeId = 9 },
                new Aircraft { Id = 75, Manufacturer = "Lockheed Martin", Model = "F-16 Fighting Falcon", Year = 2016, FlightHours = 459, Condition = "C", AircraftTypeId = 10 },
                new Aircraft { Id = 76, Manufacturer = "Lockheed Martin", Model = "F-117 Nighthawk", Year = 2003, FlightHours = 122, Condition = "A", AircraftTypeId = 11 },
                new Aircraft { Id = 77, Manufacturer = "Lockheed Martin", Model = "F-22 Raptor", Year = 2013, FlightHours = 633, Condition = "A", AircraftTypeId = 12 },
                new Aircraft { Id = 78, Manufacturer = "Lockheed Martin", Model = "A-4AR Fightinghawk", Year = 2004, FlightHours = 603, Condition = "A", AircraftTypeId = 13 },
                new Aircraft { Id = 79, Manufacturer = "Lockheed Martin", Model = "F-35 Lightning II", Year = 2000, FlightHours = 623, Condition = "A", AircraftTypeId = 14 },
                new Aircraft { Id = 80, Manufacturer = "Lockheed Martin", Model = "A-4AR Fightinghawk", Year = 2015, FlightHours = 714, Condition = "A", AircraftTypeId = 15 },
                new Aircraft { Id = 81, Manufacturer = "Lockheed Martin", Model = "F-22 Raptor", Year = 2004, FlightHours = 271, Condition = "A", AircraftTypeId = 5 },
                new Aircraft { Id = 82, Manufacturer = "Lockheed Martin", Model = "F-117 Nighthawk", Year = 2006, FlightHours = 28, Condition = "C", AircraftTypeId = 6 },
                new Aircraft { Id = 83, Manufacturer = "Lockheed Martin", Model = "F-16 Fighting Falcon", Year = 2003, FlightHours = 570, Condition = "A", AircraftTypeId = 7 },
                new Aircraft { Id = 84, Manufacturer = "Airbus", Model = "A220", Year = 2003, FlightHours = 409, Condition = "C", AircraftTypeId = 8 },
                new Aircraft { Id = 85, Manufacturer = "Airbus", Model = "A300", Year = 2000, FlightHours = 780, Condition = "B", AircraftTypeId = 9 },
                new Aircraft { Id = 86, Manufacturer = "Airbus", Model = "A310", Year = 2012, FlightHours = 243, Condition = "C", AircraftTypeId = 15 },
                new Aircraft { Id = 87, Manufacturer = "Airbus", Model = "A318", Year = 2021, FlightHours = 359, Condition = "B", AircraftTypeId = 10 },
                new Aircraft { Id = 88, Manufacturer = "Airbus", Model = "A319", Year = 2015, FlightHours = 501, Condition = "B", AircraftTypeId = 11 },
                new Aircraft { Id = 89, Manufacturer = "Airbus", Model = "A320", Year = 2001, FlightHours = 15, Condition = "C", AircraftTypeId = 12 },
                new Aircraft { Id = 90, Manufacturer = "Airbus", Model = "A321", Year = 2017, FlightHours = 62, Condition = "A", AircraftTypeId = 3 },
                new Aircraft { Id = 91, Manufacturer = "Airbus", Model = "A330", Year = 2011, FlightHours = 491, Condition = "B", AircraftTypeId = 4 },
                new Aircraft { Id = 92, Manufacturer = "Airbus", Model = "A340", Year = 2009, FlightHours = 393, Condition = "A", AircraftTypeId = 5 },
                new Aircraft { Id = 93, Manufacturer = "Airbus", Model = "A350", Year = 2010, FlightHours = 785, Condition = "B", AircraftTypeId = 6 },
                new Aircraft { Id = 94, Manufacturer = "Airbus", Model = "A380", Year = 2003, FlightHours = 223, Condition = "C", AircraftTypeId = 7 },
                new Aircraft { Id = 95, Manufacturer = "Bombardier Aerospace", Model = "CRJ700", Year = 2018, FlightHours = 101, Condition = "A", AircraftTypeId = 8 },
                new Aircraft { Id = 96, Manufacturer = "Bombardier Aerospace", Model = "CRJ900", Year = 2008, FlightHours = 280, Condition = "B", AircraftTypeId = 9 },
                new Aircraft { Id = 97, Manufacturer = "Bombardier Aerospace", Model = "Global Express", Year = 2012, FlightHours = 341, Condition = "A", AircraftTypeId = 10 },
                new Aircraft { Id = 98, Manufacturer = "Bombardier Aerospace", Model = "Learjet 75", Year = 2015, FlightHours = 210, Condition = "B", AircraftTypeId = 11 },
                new Aircraft { Id = 99, Manufacturer = "Bombardier Aerospace", Model = "Challenger 350", Year = 2006, FlightHours = 370, Condition = "C", AircraftTypeId = 12 },
                new Aircraft { Id = 100, Manufacturer = "Bombardier Aerospace", Model = "Dash 8 Q400", Year = 2007, FlightHours = 424, Condition = "A", AircraftTypeId = 13 }

);

            modelBuilder.Entity<AirportEntity>().HasData(
                new AirportEntity { Id = 1, Name = "Touat-Cheikh Sidi Mohamed Belkebir Airport", Country = "Algeria" },
                new AirportEntity { Id = 2, Name = "Cadjehoun Airport", Country = "Benin" },
                new AirportEntity { Id = 3, Name = "Sir Seretse Khama International Airport", Country = "Botswana" },
                new AirportEntity { Id = 4, Name = "Thomas Sankara International Airport Ouagadougou", Country = "Burkina Faso" },
                new AirportEntity { Id = 5, Name = "Bujumbura International Airport", Country = "Burundi" },
                new AirportEntity { Id = 6, Name = "Douala International Airport", Country = "Cameroon" },
                new AirportEntity { Id = 7, Name = "Aristides Pereira International Airport", Country = "Cape Verde" },
                new AirportEntity { Id = 8, Name = "Bangui M'Poko International Airport", Country = "Central African Republic" },
                new AirportEntity { Id = 9, Name = "N'Djamena International Airport", Country = "Chad" },
                new AirportEntity { Id = 10, Name = "Prince Said Ibrahim International Airport", Country = "Comoros" },
                new AirportEntity { Id = 11, Name = "Kisangani Bangoka International Airport", Country = "Democratic Republic of the Congo" },
                new AirportEntity { Id = 12, Name = "Agostinho-Neto International Airport", Country = "Republic of the Congo" },
                new AirportEntity { Id = 13, Name = "Sharm El Sheikh International Airport", Country = "Egypt" },
                new AirportEntity { Id = 14, Name = "Malabo International Airport", Country = "Equatorial Guinea" },
                new AirportEntity { Id = 15, Name = "Asmara International Airport", Country = "Eritrea" },
                new AirportEntity { Id = 16, Name = "King Mswati III International Airport", Country = "Eswatini" },
                new AirportEntity { Id = 17, Name = "Addis Ababa Bole International Airport", Country = "Ethiopia" },
                new AirportEntity { Id = 18, Name = "M'Vengue El Hadj Omar Bongo Ondimba International Airport", Country = "Gabon" },
                new AirportEntity { Id = 19, Name = "Banjul International Airport", Country = "The Gambia" },
                new AirportEntity { Id = 20, Name = "Kotoka International Airport", Country = "Ghana" },
                new AirportEntity { Id = 21, Name = "Conakry International Airport", Country = "Guinea" },
                new AirportEntity { Id = 22, Name = "Osvaldo Vieira International Airport", Country = "Guinea-Bissau" },
                new AirportEntity { Id = 23, Name = "Jomo Kenyatta International Airport", Country = "Kenya" },
                new AirportEntity { Id = 24, Name = "Roberts International Airport", Country = "Liberia" },
                new AirportEntity { Id = 25, Name = "Tripoli International Airport", Country = "Libya" },
                new AirportEntity { Id = 26, Name = "Ivato International Airport", Country = "Madagascar" },
                new AirportEntity { Id = 27, Name = "Lilongwe International Airport", Country = "Malawi" },
                new AirportEntity { Id = 28, Name = "Modibo Keita International Airport", Country = "Mali" },
                new AirportEntity { Id = 29, Name = "Nouakchottoumtounsy International Airport", Country = "Mauritania" },
                new AirportEntity { Id = 30, Name = "Sir Seewoosagur Ramgoolam International Airport", Country = "Mauritius" },
                new AirportEntity { Id = 31, Name = "Dzaoudzi Pamandzi International Airport", Country = "Mayotte" },
                new AirportEntity { Id = 32, Name = "Tangier Ibn Battouta Airport", Country = "Morocco" },
                new AirportEntity { Id = 33, Name = "Maputo International Airport", Country = "Mozambique" },
                new AirportEntity { Id = 34, Name = "Hosea Kutako International Airport", Country = "Namibia" },
                new AirportEntity { Id = 35, Name = "Mallam Aminu Kano International Airport", Country = "Nigeria" },
                new AirportEntity { Id = 36, Name = "Saint Helena Airport", Country = "Saint Helena, Ascension and Tristan da Cunha" },
                new AirportEntity { Id = 37, Name = "Aden Adde International Airport", Country = "Somalia" },
                new AirportEntity { Id = 38, Name = "Kruger Mpumalanga International Airport", Country = "South Africa" },
                new AirportEntity { Id = 39, Name = "Monastir Habib Bourguiba International Airport", Country = "Tunisia" },
                new AirportEntity { Id = 40, Name = "Punta Cana International Airport", Country = "Dominican Republic" },
                new AirportEntity { Id = 41, Name = "Providenciales Airport", Country = "Turks and Caicos Islands" },
                new AirportEntity { Id = 42, Name = "Winnipeg James Armstrong Richardson International Airport", Country = "Canada" },
                new AirportEntity { Id = 43, Name = "Miguel Hidalgo y Costilla Guadalajara International Airport", Country = "Mexico" },
                new AirportEntity { Id = 44, Name = "Logan International Airport", Country = "United States" },
                new AirportEntity { Id = 45, Name = "Presidente Castro Pinto International Airport", Country = "Brazil" },
                new AirportEntity { Id = 46, Name = "Nursultan Nazarbayev International Airport", Country = "Kazakhstan" },
                new AirportEntity { Id = 47, Name = "Chubu Centrair International Airport", Country = "Japan" },
                new AirportEntity { Id = 48, Name = "55759 Valley Edge Pass", Country = "" },
                new AirportEntity { Id = 49, Name = "Guiyang Longdongbao International Airport", Country = "China" },
                new AirportEntity { Id = 50, Name = "Netaji Subhas Chandra Bose International Airport", Country = "India" }
);

            modelBuilder.Entity<PilotAircraft>().HasData(
                new PilotAircraft { AircraftId = 94, PilotId = 4 },
                new PilotAircraft { AircraftId = 22, PilotId = 33 },
                new PilotAircraft { AircraftId = 60, PilotId = 26 },
                new PilotAircraft { AircraftId = 5, PilotId = 12 },
                new PilotAircraft { AircraftId = 69, PilotId = 41 },
                new PilotAircraft { AircraftId = 90, PilotId = 37 },
                new PilotAircraft { AircraftId = 33, PilotId = 24 },
                new PilotAircraft { AircraftId = 20, PilotId = 49 },
                new PilotAircraft { AircraftId = 66, PilotId = 10 },
                new PilotAircraft { AircraftId = 37, PilotId = 35 },
                new PilotAircraft { AircraftId = 67, PilotId = 42 },
                new PilotAircraft { AircraftId = 96, PilotId = 6 },
                new PilotAircraft { AircraftId = 99, PilotId = 5 },
                new PilotAircraft { AircraftId = 85, PilotId = 2 },
                new PilotAircraft { AircraftId = 77, PilotId = 37 },
                new PilotAircraft { AircraftId = 100, PilotId = 2 },
                new PilotAircraft { AircraftId = 39, PilotId = 10 },
                new PilotAircraft { AircraftId = 21, PilotId = 36 },
                new PilotAircraft { AircraftId = 80, PilotId = 39 },
                new PilotAircraft { AircraftId = 4, PilotId = 11 },
                new PilotAircraft { AircraftId = 49, PilotId = 9 },
                new PilotAircraft { AircraftId = 71, PilotId = 50 },
                new PilotAircraft { AircraftId = 57, PilotId = 16 },
                new PilotAircraft { AircraftId = 16, PilotId = 31 },
                new PilotAircraft { AircraftId = 4, PilotId = 14 },
                new PilotAircraft { AircraftId = 60, PilotId = 25 },
                new PilotAircraft { AircraftId = 36, PilotId = 1 },
                new PilotAircraft { AircraftId = 81, PilotId = 38 },
                new PilotAircraft { AircraftId = 68, PilotId = 41 },
                new PilotAircraft { AircraftId = 6, PilotId = 50 },
                new PilotAircraft { AircraftId = 65, PilotId = 39 },
                new PilotAircraft { AircraftId = 48, PilotId = 20 },
                new PilotAircraft { AircraftId = 30, PilotId = 18 },
                new PilotAircraft { AircraftId = 90, PilotId = 27 },
                new PilotAircraft { AircraftId = 15, PilotId = 30 },
                new PilotAircraft { AircraftId = 57, PilotId = 33 },
                new PilotAircraft { AircraftId = 96, PilotId = 19 },
                new PilotAircraft { AircraftId = 81, PilotId = 26 },
                new PilotAircraft { AircraftId = 5, PilotId = 22 },
                new PilotAircraft { AircraftId = 56, PilotId = 45 },
                new PilotAircraft { AircraftId = 7, PilotId = 18 },
                new PilotAircraft { AircraftId = 4, PilotId = 48 },
                new PilotAircraft { AircraftId = 93, PilotId = 7 },
                new PilotAircraft { AircraftId = 20, PilotId = 8 },
                new PilotAircraft { AircraftId = 23, PilotId = 17 },
                new PilotAircraft { AircraftId = 84, PilotId = 3 },
                new PilotAircraft { AircraftId = 21, PilotId = 40 },
                new PilotAircraft { AircraftId = 33, PilotId = 8 },
                new PilotAircraft { AircraftId = 72, PilotId = 7 },
                new PilotAircraft { AircraftId = 72, PilotId = 37 },
                new PilotAircraft { AircraftId = 77, PilotId = 43 },
                new PilotAircraft { AircraftId = 30, PilotId = 4 },
                new PilotAircraft { AircraftId = 68, PilotId = 38 },
                new PilotAircraft { AircraftId = 3, PilotId = 3 },
                new PilotAircraft { AircraftId = 52, PilotId = 32 },
                new PilotAircraft { AircraftId = 70, PilotId = 30 },
                new PilotAircraft { AircraftId = 72, PilotId = 21 },
                new PilotAircraft { AircraftId = 28, PilotId = 9 },
                new PilotAircraft { AircraftId = 100, PilotId = 3 },
                new PilotAircraft { AircraftId = 32, PilotId = 36 },
                new PilotAircraft { AircraftId = 47, PilotId = 13 },
                new PilotAircraft { AircraftId = 55, PilotId = 38 },
                new PilotAircraft { AircraftId = 55, PilotId = 18 },
                new PilotAircraft { AircraftId = 21, PilotId = 24 },
                new PilotAircraft { AircraftId = 85, PilotId = 29 },
                new PilotAircraft { AircraftId = 86, PilotId = 22 },
                new PilotAircraft { AircraftId = 3, PilotId = 11 },
                new PilotAircraft { AircraftId = 28, PilotId = 49 },
                new PilotAircraft { AircraftId = 82, PilotId = 42 },
                new PilotAircraft { AircraftId = 25, PilotId = 36 },
                new PilotAircraft { AircraftId = 42, PilotId = 28 },
                new PilotAircraft { AircraftId = 59, PilotId = 20 },
                new PilotAircraft { AircraftId = 20, PilotId = 3 },
                new PilotAircraft { AircraftId = 70, PilotId = 21 },
                new PilotAircraft { AircraftId = 84, PilotId = 7 },
                new PilotAircraft { AircraftId = 96, PilotId = 26 },
                new PilotAircraft { AircraftId = 89, PilotId = 47 },
                new PilotAircraft { AircraftId = 46, PilotId = 19 },
                new PilotAircraft { AircraftId = 42, PilotId = 7 },
                new PilotAircraft { AircraftId = 10, PilotId = 9 },
                new PilotAircraft { AircraftId = 38, PilotId = 15 },
                new PilotAircraft { AircraftId = 94, PilotId = 14 },
                new PilotAircraft { AircraftId = 18, PilotId = 4 },
                new PilotAircraft { AircraftId = 5, PilotId = 38 },
                new PilotAircraft { AircraftId = 48, PilotId = 2 },
                new PilotAircraft { AircraftId = 38, PilotId = 20 },
                new PilotAircraft { AircraftId = 55, PilotId = 23 },
                new PilotAircraft { AircraftId = 25, PilotId = 33 },
                new PilotAircraft { AircraftId = 26, PilotId = 37 },
                new PilotAircraft { AircraftId = 12, PilotId = 35 },
                new PilotAircraft { AircraftId = 48, PilotId = 26 },
                new PilotAircraft { AircraftId = 42, PilotId = 27 },
                new PilotAircraft { AircraftId = 5, PilotId = 19 },
                new PilotAircraft { AircraftId = 10, PilotId = 7 },
                new PilotAircraft { AircraftId = 45, PilotId = 47 },
                new PilotAircraft { AircraftId = 80, PilotId = 29 },
                new PilotAircraft { AircraftId = 47, PilotId = 48 },
                new PilotAircraft { AircraftId = 67, PilotId = 47 },
                new PilotAircraft { AircraftId = 14, PilotId = 40 },
                new PilotAircraft { AircraftId = 6, PilotId = 18 }
            );

            modelBuilder.Entity<FlightDestination>().HasData(
                new FlightDestination { Id = 1, AirportId = 29, Departure = DateTime.Parse("2020-01-01 01:26:11"), AircraftId = 29, PassengerId = 86, TicketPrice = 4096.92m },
                new FlightDestination { Id = 2, AirportId = 1, Departure = DateTime.Parse("2020-04-26 17:51:13"), AircraftId = 80, PassengerId = 16, TicketPrice = 1904.47m },
                new FlightDestination { Id = 3, AirportId = 27, Departure = DateTime.Parse("2020-02-18 14:00:01"), AircraftId = 25, PassengerId = 86, TicketPrice = 404.01m },
                new FlightDestination { Id = 4, AirportId = 3, Departure = DateTime.Parse("2020-03-22 04:23:48"), AircraftId = 92, PassengerId = 59, TicketPrice = 2490.24m },
                new FlightDestination { Id = 5, AirportId = 34, Departure = DateTime.Parse("2021-04-17 12:30:28"), AircraftId = 74, PassengerId = 72, TicketPrice = 405.83m },
                new FlightDestination { Id = 6, AirportId = 42, Departure = DateTime.Parse("2020-09-21 22:50:50"), AircraftId = 1, PassengerId = 69, TicketPrice = 1880.23m },
                new FlightDestination { Id = 7, AirportId = 31, Departure = DateTime.Parse("2020-10-16 04:58:11"), AircraftId = 78, PassengerId = 4, TicketPrice = 2111.93m },
                new FlightDestination { Id = 8, AirportId = 15, Departure = DateTime.Parse("2020-01-13 05:32:42"), AircraftId = 100, PassengerId = 89, TicketPrice = 2110.56m },
                new FlightDestination { Id = 9, AirportId = 41, Departure = DateTime.Parse("2020-02-06 22:32:14"), AircraftId = 22, PassengerId = 48, TicketPrice = 4100.49m },
                new FlightDestination { Id = 10, AirportId = 11, Departure = DateTime.Parse("2020-06-06 22:44:50"), AircraftId = 63, PassengerId = 92, TicketPrice = 150.56m },
                new FlightDestination { Id = 11, AirportId = 1, Departure = DateTime.Parse("2020-08-26 06:09:21"), AircraftId = 83, PassengerId = 63, TicketPrice = 290.98m },
                new FlightDestination { Id = 12, AirportId = 12, Departure = DateTime.Parse("2021-04-20 09:34:41"), AircraftId = 93, PassengerId = 53, TicketPrice = 930.27m },
                new FlightDestination { Id = 13, AirportId = 28, Departure = DateTime.Parse("2020-02-04 04:59:33"), AircraftId = 80, PassengerId = 89, TicketPrice = 3280.36m },
                new FlightDestination { Id = 14, AirportId = 31, Departure = DateTime.Parse("2021-01-19 11:05:43"), AircraftId = 13, PassengerId = 65, TicketPrice = 3083.05m },
                new FlightDestination { Id = 15, AirportId = 18, Departure = DateTime.Parse("2020-04-17 23:42:06"), AircraftId = 49, PassengerId = 63, TicketPrice = 3087.56m },
                new FlightDestination { Id = 16, AirportId = 5, Departure = DateTime.Parse("2021-02-06 01:03:30"), AircraftId = 37, PassengerId = 61, TicketPrice = 1780.60m },
                new FlightDestination { Id = 17, AirportId = 28, Departure = DateTime.Parse("2020-10-29 05:10:21"), AircraftId = 47, PassengerId = 19, TicketPrice = 300.46m },
                new FlightDestination { Id = 18, AirportId = 12, Departure = DateTime.Parse("2021-04-18 11:35:23"), AircraftId = 5, PassengerId = 79, TicketPrice = 2180.54m },
                new FlightDestination { Id = 19, AirportId = 21, Departure = DateTime.Parse("2020-07-03 21:38:23"), AircraftId = 77, PassengerId = 28, TicketPrice = 1801.36m },
                new FlightDestination { Id = 20, AirportId = 18, Departure = DateTime.Parse("2020-02-27 06:06:45"), AircraftId = 4, PassengerId = 28, TicketPrice = 440.72m },
                new FlightDestination { Id = 21, AirportId = 34, Departure = DateTime.Parse("2020-08-02 15:43:34"), AircraftId = 50, PassengerId = 88, TicketPrice = 3010.46m },
                new FlightDestination { Id = 22, AirportId = 27, Departure = DateTime.Parse("2020-04-10 23:14:06"), AircraftId = 33, PassengerId = 86, TicketPrice = 160.99m },
                new FlightDestination { Id = 23, AirportId = 17, Departure = DateTime.Parse("2021-04-30 06:25:18"), AircraftId = 36, PassengerId = 78, TicketPrice = 300.07m },
                new FlightDestination { Id = 24, AirportId = 42, Departure = DateTime.Parse("2020-03-24 21:08:22"), AircraftId = 6, PassengerId = 70, TicketPrice = 2170.03m },
                new FlightDestination { Id = 25, AirportId = 6, Departure = DateTime.Parse("2020-10-01 00:35:46"), AircraftId = 33, PassengerId = 92, TicketPrice = 470.11m },
                new FlightDestination { Id = 26, AirportId = 11, Departure = DateTime.Parse("2021-02-02 04:44:05"), AircraftId = 55, PassengerId = 88, TicketPrice = 460.57m },
                new FlightDestination { Id = 27, AirportId = 13, Departure = DateTime.Parse("2021-05-02 12:52:14"), AircraftId = 2, PassengerId = 31, TicketPrice = 3091.31m },
                new FlightDestination { Id = 28, AirportId = 42, Departure = DateTime.Parse("2020-11-11 11:15:42"), AircraftId = 44, PassengerId = 37, TicketPrice = 2130.86m },
                new FlightDestination { Id = 29, AirportId = 31, Departure = DateTime.Parse("2020-11-14 07:12:00"), AircraftId = 20, PassengerId = 78, TicketPrice = 1120.51m },
                new FlightDestination { Id = 30, AirportId = 23, Departure = DateTime.Parse("2021-05-25 02:55:43"), AircraftId = 45, PassengerId = 41, TicketPrice = 405.97m },
                new FlightDestination { Id = 31, AirportId = 4, Departure = DateTime.Parse("2020-12-12 03:06:06"), AircraftId = 79, PassengerId = 19, TicketPrice = 260.58m },
                new FlightDestination { Id = 32, AirportId = 5, Departure = DateTime.Parse("2020-09-10 01:55:19"), AircraftId = 75, PassengerId = 22, TicketPrice = 3690.22m },
                new FlightDestination { Id = 33, AirportId = 10, Departure = DateTime.Parse("2020-02-06 02:03:35"), AircraftId = 76, PassengerId = 8, TicketPrice = 1017.93m },
                new FlightDestination { Id = 34, AirportId = 16, Departure = DateTime.Parse("2020-06-13 10:53:40"), AircraftId = 82, PassengerId = 86, TicketPrice = 3190.57m },
                new FlightDestination { Id = 35, AirportId = 3, Departure = DateTime.Parse("2020-01-15 09:11:40"), AircraftId = 77, PassengerId = 12, TicketPrice = 380.32m },
                new FlightDestination { Id = 36, AirportId = 1, Departure = DateTime.Parse("2020-03-02 21:56:45"), AircraftId = 38, PassengerId = 57, TicketPrice = 350.42m },
                new FlightDestination { Id = 37, AirportId = 39, Departure = DateTime.Parse("2020-07-19 18:01:03"), AircraftId = 80, PassengerId = 86, TicketPrice = 1150.16m },
                new FlightDestination { Id = 38, AirportId = 39, Departure = DateTime.Parse("2020-10-14 23:26:43"), AircraftId = 67, PassengerId = 14, TicketPrice = 780.61m },
                new FlightDestination { Id = 39, AirportId = 2, Departure = DateTime.Parse("2021-02-17 21:18:51"), AircraftId = 2, PassengerId = 64, TicketPrice = 1130.19m },
                new FlightDestination { Id = 40, AirportId = 36, Departure = DateTime.Parse("2020-01-05 11:05:38"), AircraftId = 14, PassengerId = 65, TicketPrice = 1580.50m },
                new FlightDestination { Id = 41, AirportId = 6, Departure = DateTime.Parse("2020-08-10 11:33:10"), AircraftId = 20, PassengerId = 64, TicketPrice = 1800.43m },
                new FlightDestination { Id = 42, AirportId = 14, Departure = DateTime.Parse("2020-04-20 23:28:53"), AircraftId = 90, PassengerId = 24, TicketPrice = 4080.54m },
                new FlightDestination { Id = 43, AirportId = 40, Departure = DateTime.Parse("2020-04-24 23:48:04"), AircraftId = 34, PassengerId = 4, TicketPrice = 490.84m },
                new FlightDestination { Id = 44, AirportId = 22, Departure = DateTime.Parse("2020-06-25 18:16:14"), AircraftId = 1, PassengerId = 26, TicketPrice = 730.22m },
                new FlightDestination { Id = 45, AirportId = 12, Departure = DateTime.Parse("2020-01-20 14:27:26"), AircraftId = 18, PassengerId = 49, TicketPrice = 260.61m },
                new FlightDestination { Id = 46, AirportId = 27, Departure = DateTime.Parse("2021-01-15 15:23:51"), AircraftId = 27, PassengerId = 42, TicketPrice = 380.22m },
                new FlightDestination { Id = 47, AirportId = 41, Departure = DateTime.Parse("2021-05-19 02:24:33"), AircraftId = 33, PassengerId = 26, TicketPrice = 230.61m },
                new FlightDestination { Id = 48, AirportId = 10, Departure = DateTime.Parse("2020-02-04 23:30:05"), AircraftId = 59, PassengerId = 88, TicketPrice = 260.32m },
                new FlightDestination { Id = 49, AirportId = 4, Departure = DateTime.Parse("2020-12-29 06:46:06"), AircraftId = 28, PassengerId = 15, TicketPrice = 280.52m },
                new FlightDestination { Id = 50, AirportId = 21, Departure = DateTime.Parse("2020-07-25 23:22:34"), AircraftId = 44, PassengerId = 81, TicketPrice = 680.22m },
                new FlightDestination { Id = 51, AirportId = 33, Departure = DateTime.Parse("2020-04-19 14:32:41"), AircraftId = 84, PassengerId = 29, TicketPrice = 470.16m },
                new FlightDestination { Id = 52, AirportId = 2, Departure = DateTime.Parse("2020-01-04 18:44:46"), AircraftId = 56, PassengerId = 43, TicketPrice = 300.88m },
                new FlightDestination { Id = 53, AirportId = 43, Departure = DateTime.Parse("2020-03-25 14:42:08"), AircraftId = 35, PassengerId = 92, TicketPrice = 900.26m },
                new FlightDestination { Id = 54, AirportId = 29, Departure = DateTime.Parse("2021-04-05 03:46:29"), AircraftId = 83, PassengerId = 11, TicketPrice = 690.20m },
                new FlightDestination { Id = 55, AirportId = 1, Departure = DateTime.Parse("2021-01-05 19:38:45"), AircraftId = 64, PassengerId = 28, TicketPrice = 500.52m },
                new FlightDestination { Id = 56, AirportId = 19, Departure = DateTime.Parse("2020-03-06 04:54:13"), AircraftId = 24, PassengerId = 54, TicketPrice = 1180.14m },
                new FlightDestination { Id = 57, AirportId = 31, Departure = DateTime.Parse("2020-05-29 22:36:38"), AircraftId = 81, PassengerId = 18, TicketPrice = 1090.53m },
                new FlightDestination { Id = 58, AirportId = 32, Departure = DateTime.Parse("2020-01-05 22:15:12"), AircraftId = 19, PassengerId = 75, TicketPrice = 480.44m },
                new FlightDestination { Id = 59, AirportId = 7, Departure = DateTime.Parse("2020-12-07 03:19:32"), AircraftId = 26, PassengerId = 38, TicketPrice = 540.29m },
                new FlightDestination { Id = 60, AirportId = 14, Departure = DateTime.Parse("2020-05-10 11:02:01"), AircraftId = 62, PassengerId = 16, TicketPrice = 670.29m },
                new FlightDestination { Id = 61, AirportId = 35, Departure = DateTime.Parse("2020-06-23 07:05:05"), AircraftId = 25, PassengerId = 6, TicketPrice = 1020.18m },
                new FlightDestination { Id = 62, AirportId = 15, Departure = DateTime.Parse("2020-09-26 15:14:23"), AircraftId = 84, PassengerId = 5, TicketPrice = 1150.00m },
                new FlightDestination { Id = 63, AirportId = 18, Departure = DateTime.Parse("2021-01-17 06:43:22"), AircraftId = 21, PassengerId = 74, TicketPrice = 1180.50m },
                new FlightDestination { Id = 64, AirportId = 22, Departure = DateTime.Parse("2020-12-31 18:54:00"), AircraftId = 88, PassengerId = 77, TicketPrice = 410.22m },
                new FlightDestination { Id = 65, AirportId = 8, Departure = DateTime.Parse("2020-11-12 21:39:49"), AircraftId = 6, PassengerId = 10, TicketPrice = 490.70m },
                new FlightDestination { Id = 66, AirportId = 30, Departure = DateTime.Parse("2021-02-20 03:41:37"), AircraftId = 29, PassengerId = 61, TicketPrice = 730.10m },
                new FlightDestination { Id = 67, AirportId = 17, Departure = DateTime.Parse("2021-03-16 02:18:22"), AircraftId = 40, PassengerId = 21, TicketPrice = 820.45m },
                new FlightDestination { Id = 68, AirportId = 5, Departure = DateTime.Parse("2021-04-18 22:02:53"), AircraftId = 51, PassengerId = 82, TicketPrice = 380.60m },
                new FlightDestination { Id = 69, AirportId = 13, Departure = DateTime.Parse("2020-01-10 09:14:04"), AircraftId = 37, PassengerId = 57, TicketPrice = 430.16m },
                new FlightDestination { Id = 70, AirportId = 25, Departure = DateTime.Parse("2020-08-21 19:38:14"), AircraftId = 60, PassengerId = 69, TicketPrice = 880.00m },
                new FlightDestination { Id = 71, AirportId = 39, Departure = DateTime.Parse("2020-06-27 21:03:09"), AircraftId = 18, PassengerId = 30, TicketPrice = 420.85m },
                new FlightDestination { Id = 72, AirportId = 4, Departure = DateTime.Parse("2020-03-15 08:26:54"), AircraftId = 12, PassengerId = 85, TicketPrice = 1090.52m },
                new FlightDestination { Id = 73, AirportId = 24, Departure = DateTime.Parse("2020-02-17 23:07:36"), AircraftId = 42, PassengerId = 45, TicketPrice = 540.99m },
                new FlightDestination { Id = 74, AirportId = 36, Departure = DateTime.Parse("2020-07-04 05:45:01"), AircraftId = 65, PassengerId = 20, TicketPrice = 690.30m },
                new FlightDestination { Id = 75, AirportId = 34, Departure = DateTime.Parse("2020-05-12 04:25:50"), AircraftId = 17, PassengerId = 25, TicketPrice = 310.56m },
                new FlightDestination { Id = 76, AirportId = 28, Departure = DateTime.Parse("2020-01-30 18:49:47"), AircraftId = 69, PassengerId = 7, TicketPrice = 250.36m },
                new FlightDestination { Id = 77, AirportId = 3, Departure = DateTime.Parse("2020-12-22 20:17:36"), AircraftId = 11, PassengerId = 39, TicketPrice = 750.27m },
                new FlightDestination { Id = 78, AirportId = 26, Departure = DateTime.Parse("2020-09-06 12:02:51"), AircraftId = 73, PassengerId = 53, TicketPrice = 520.24m },
                new FlightDestination { Id = 79, AirportId = 11, Departure = DateTime.Parse("2020-04-25 07:58:17"), AircraftId = 54, PassengerId = 50, TicketPrice = 420.13m },
                new FlightDestination { Id = 80, AirportId = 7, Departure = DateTime.Parse("2020-11-19 01:43:38"), AircraftId = 39, PassengerId = 60, TicketPrice = 120.34m },
                new FlightDestination { Id = 81, AirportId = 9, Departure = DateTime.Parse("2020-02-28 06:12:24"), AircraftId = 9, PassengerId = 11, TicketPrice = 130.54m },
                new FlightDestination { Id = 82, AirportId = 20, Departure = DateTime.Parse("2020-03-12 08:29:01"), AircraftId = 32, PassengerId = 33, TicketPrice = 420.67m },
                new FlightDestination { Id = 83, AirportId = 1, Departure = DateTime.Parse("2020-10-04 16:44:45"), AircraftId = 15, PassengerId = 49, TicketPrice = 270.80m },
                new FlightDestination { Id = 84, AirportId = 38, Departure = DateTime.Parse("2020-06-13 22:17:51"), AircraftId = 13, PassengerId = 12, TicketPrice = 210.43m },
                new FlightDestination { Id = 85, AirportId = 16, Departure = DateTime.Parse("2020-09-15 09:01:31"), AircraftId = 7, PassengerId = 25, TicketPrice = 460.59m },
                new FlightDestination { Id = 86, AirportId = 15, Departure = DateTime.Parse("2020-01-27 07:35:50"), AircraftId = 58, PassengerId = 19, TicketPrice = 390.28m },
                new FlightDestination { Id = 87, AirportId = 35, Departure = DateTime.Parse("2020-04-14 20:41:37"), AircraftId = 10, PassengerId = 34, TicketPrice = 410.91m },
                new FlightDestination { Id = 88, AirportId = 23, Departure = DateTime.Parse("2020-05-16 23:59:01"), AircraftId = 53, PassengerId = 44, TicketPrice = 370.82m },
                new FlightDestination { Id = 89, AirportId = 30, Departure = DateTime.Parse("2020-11-29 13:44:36"), AircraftId = 41, PassengerId = 17, TicketPrice = 330.75m },
                new FlightDestination { Id = 90, AirportId = 37, Departure = DateTime.Parse("2020-03-03 12:21:42"), AircraftId = 8, PassengerId = 23, TicketPrice = 290.48m },
                new FlightDestination { Id = 91, AirportId = 22, Departure = DateTime.Parse("2020-08-20 11:58:59"), AircraftId = 31, PassengerId = 13, TicketPrice = 420.10m },
                new FlightDestination { Id = 92, AirportId = 33, Departure = DateTime.Parse("2020-09-17 18:22:55"), AircraftId = 72, PassengerId = 48, TicketPrice = 250.61m },
                new FlightDestination { Id = 93, AirportId = 25, Departure = DateTime.Parse("2020-02-28 09:44:23"), AircraftId = 66, PassengerId = 59, TicketPrice = 400.12m },
                new FlightDestination { Id = 94, AirportId = 28, Departure = DateTime.Parse("2020-07-30 15:07:06"), AircraftId = 23, PassengerId = 14, TicketPrice = 460.90m },
                new FlightDestination { Id = 95, AirportId = 6, Departure = DateTime.Parse("2020-04-01 20:39:38"), AircraftId = 16, PassengerId = 9, TicketPrice = 330.22m },
                new FlightDestination { Id = 96, AirportId = 10, Departure = DateTime.Parse("2020-05-12 18:53:19"), AircraftId = 61, PassengerId = 66, TicketPrice = 390.30m },
                new FlightDestination { Id = 97, AirportId = 13, Departure = DateTime.Parse("2020-06-23 17:10:24"), AircraftId = 43, PassengerId = 71, TicketPrice = 350.43m },
                new FlightDestination { Id = 98, AirportId = 18, Departure = DateTime.Parse("2020-10-14 11:42:37"), AircraftId = 30, PassengerId = 24, TicketPrice = 380.80m },
                new FlightDestination { Id = 99, AirportId = 20, Departure = DateTime.Parse("2020-11-15 15:29:42"), AircraftId = 57, PassengerId = 27, TicketPrice = 310.19m },
                new FlightDestination { Id = 100, AirportId = 42, Departure = DateTime.Parse("2020-12-16 21:08:50"), AircraftId = 68, PassengerId = 31, TicketPrice = 420.32m }
            );


            base.OnModelCreating(modelBuilder);
        }

    }
}
