// <auto-generated />
using Airport.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airport.DAL.EF.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    [Migration("20250628202249_MigrationSeeding1")]
    partial class MigrationSeeding1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Airport.DAL.EF.Entities.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightHours")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftTypeId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.AircraftType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AircraftTypes");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.AirportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.FlightDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirportId");

                    b.HasIndex("PassengerId");

                    b.ToTable("FlightDestinations");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "KalindiKeningham@gmail.com",
                            FullName = "Kalindi Keningham"
                        },
                        new
                        {
                            Id = 2,
                            Email = "LoisLeidle@gmail.com",
                            FullName = "Lois Leidle"
                        },
                        new
                        {
                            Id = 3,
                            Email = "CasiFarens@gmail.com",
                            FullName = "Casi Farens"
                        },
                        new
                        {
                            Id = 4,
                            Email = "JannaKellert@gmail.com",
                            FullName = "Janna Kellert"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ConnyBarnwille@gmail.com",
                            FullName = "Conny Barnwille"
                        },
                        new
                        {
                            Id = 6,
                            Email = "PierretteDunmuir@gmail.com",
                            FullName = "Pierrette Dunmuir"
                        },
                        new
                        {
                            Id = 7,
                            Email = "JasenYeldham@gmail.com",
                            FullName = "Jasen Yeldham"
                        },
                        new
                        {
                            Id = 8,
                            Email = "JosiHammelberg@gmail.com",
                            FullName = "Josi Hammelberg"
                        },
                        new
                        {
                            Id = 9,
                            Email = "UrsulinaPartner@gmail.com",
                            FullName = "Ursulina Partner"
                        },
                        new
                        {
                            Id = 10,
                            Email = "MerisShale@gmail.com",
                            FullName = "Meris Shale"
                        },
                        new
                        {
                            Id = 11,
                            Email = "CollineDann@gmail.com",
                            FullName = "Colline Dannme"
                        },
                        new
                        {
                            Id = 12,
                            Email = "JoyannGarrettson@gmail.com",
                            FullName = "Joyann Garrettson"
                        },
                        new
                        {
                            Id = 13,
                            Email = "ShaneArr@gmail.com",
                            FullName = "Shane Arorbe"
                        },
                        new
                        {
                            Id = 14,
                            Email = "OwenStrivens@gmail.com",
                            FullName = "Owen Strivens"
                        },
                        new
                        {
                            Id = 15,
                            Email = "MoynaBosnell@gmail.com",
                            FullName = "Moyna Bosnell"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Henrik@gmail.com",
                            FullName = "Henrik Sivyer"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Cullan@gmail.com",
                            FullName = "Cullan Dogerty"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Aitken@gmail.com",
                            FullName = "Jens Aitken"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Kryszkiecicz@gmail.com",
                            FullName = "Lorilee Kryszkiecicz"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Myrta@gmail.com",
                            FullName = "Myrta Soggete"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Craig@gmail.com",
                            FullName = "Craig Backeren"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Plackstone@gmail.com",
                            FullName = "Jacquelynn Plackstone"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Gerwood@gmail.com",
                            FullName = "Therese Gerwood"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Montacute@gmail.com",
                            FullName = "Jefferson Montacute"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Elgar@gmail.com",
                            FullName = "Jameson Elgarerson"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Shalders@gmail.com",
                            FullName = "Gilberte Shalders"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Simony@gmail.com",
                            FullName = "Siegfried Simony"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Deem@gmail.com",
                            FullName = "Kimball Deemond"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Ruddom@gmail.com",
                            FullName = "Sascha Ruddom"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Janelle Southern@gmail.com",
                            FullName = "Janelle Southern"
                        },
                        new
                        {
                            Id = 31,
                            Email = "ChaunceTaffe@gmail.com",
                            FullName = "Chaunce Taffe"
                        },
                        new
                        {
                            Id = 32,
                            Email = "DanteSagerson@gmail.com",
                            FullName = "Dante Sagerson"
                        },
                        new
                        {
                            Id = 33,
                            Email = "CareyFlannery@gmail.com",
                            FullName = "Carey Flannery"
                        },
                        new
                        {
                            Id = 34,
                            Email = "LizzieIscowitz@gmail.com",
                            FullName = "Lizzie Iscowitz"
                        },
                        new
                        {
                            Id = 35,
                            Email = "ZekeRowston@gmail.com",
                            FullName = "Zeke Rowston"
                        },
                        new
                        {
                            Id = 36,
                            Email = "AdelleKurten@gmail.com",
                            FullName = "Adelle Kurten"
                        },
                        new
                        {
                            Id = 37,
                            Email = "RollandTrevna@gmail.com",
                            FullName = "Rolland Trevna"
                        },
                        new
                        {
                            Id = 38,
                            Email = "GwynneBleakley@gmail.com",
                            FullName = "Gwynne Bleakley"
                        },
                        new
                        {
                            Id = 39,
                            Email = "DarbyRothert@gmail.com",
                            FullName = "Darby Rothert"
                        },
                        new
                        {
                            Id = 40,
                            Email = "MeridelStraker@gmail.com",
                            FullName = "Meridel Straker"
                        },
                        new
                        {
                            Id = 41,
                            Email = "RaynorDobbison@gmail.com",
                            FullName = "Raynor Dobbison"
                        },
                        new
                        {
                            Id = 42,
                            Email = "BurnabyBlackater@gmail.com",
                            FullName = "Burnaby Blackater"
                        },
                        new
                        {
                            Id = 43,
                            Email = "YulMoseby@gmail.com",
                            FullName = "Yulin Moseby"
                        },
                        new
                        {
                            Id = 44,
                            Email = "MilesScruby@gmail.com",
                            FullName = "Miles Scruby"
                        },
                        new
                        {
                            Id = 45,
                            Email = "JeanineGerren@gmail.com",
                            FullName = "Jeanine Gerren"
                        },
                        new
                        {
                            Id = 46,
                            Email = "CarmelLendrem@gmail.com",
                            FullName = "Carmel Lendrem"
                        },
                        new
                        {
                            Id = 47,
                            Email = "AllsunKelleher@gmail.com",
                            FullName = "Allsun O' Kelleher"
                        },
                        new
                        {
                            Id = 48,
                            Email = "LanitaCrockatt@gmail.com",
                            FullName = "Lanita Crockatt"
                        },
                        new
                        {
                            Id = 49,
                            Email = "GeorgesLanston@gmail.com",
                            FullName = "Georges Lanston"
                        },
                        new
                        {
                            Id = 50,
                            Email = "AbbeyPedri@gmail.com",
                            FullName = "Abbey Pedrinson"
                        },
                        new
                        {
                            Id = 51,
                            Email = "MichealNewtown@gmail.com",
                            FullName = "Micheal Newtown"
                        },
                        new
                        {
                            Id = 52,
                            Email = "SariChicotti@gmail.com",
                            FullName = "Sari Chicotti"
                        },
                        new
                        {
                            Id = 53,
                            Email = "GibbieLiggens@gmail.com",
                            FullName = "Gibbie Liggens"
                        },
                        new
                        {
                            Id = 54,
                            Email = "OdeleSinncock@gmail.com1",
                            FullName = "Odele Sinncock"
                        },
                        new
                        {
                            Id = 55,
                            Email = "TishaPatey@gmail.com",
                            FullName = "Tisha Paterson"
                        },
                        new
                        {
                            Id = 56,
                            Email = "MarieleDrinkhall@gmail.com",
                            FullName = "Mariele Drinkhall"
                        },
                        new
                        {
                            Id = 57,
                            Email = "RaymundClace@gmail.com",
                            FullName = "Raymund Clacenson"
                        },
                        new
                        {
                            Id = 58,
                            Email = "JoshuahDuckers@gmail.com",
                            FullName = "Joshuah Duckers"
                        },
                        new
                        {
                            Id = 59,
                            Email = "KelcyViccary@gmail.com",
                            FullName = "Kelcy Viccary"
                        },
                        new
                        {
                            Id = 60,
                            Email = "KayleePonten@gmail.com",
                            FullName = "Kaylee Ponten"
                        },
                        new
                        {
                            Id = 61,
                            Email = "MadyViccary@gmail.com",
                            FullName = "Mady Viccary"
                        },
                        new
                        {
                            Id = 62,
                            Email = "MattieHampton@gmail.com",
                            FullName = "Mattie Hampton"
                        },
                        new
                        {
                            Id = 63,
                            Email = "KayleeCoushe@gmail.com",
                            FullName = "Kaylee Coushe"
                        },
                        new
                        {
                            Id = 64,
                            Email = "LucitaRobelet@gmail.com",
                            FullName = "Lucita Robelet"
                        },
                        new
                        {
                            Id = 65,
                            Email = "FindleyIacoboni@gmail.com",
                            FullName = "Findley Iacoboni"
                        },
                        new
                        {
                            Id = 66,
                            Email = "AllanWedge@gmail.com",
                            FullName = "Allan Wedge"
                        },
                        new
                        {
                            Id = 67,
                            Email = "CordeyTremblet@gmail.com",
                            FullName = "Cordey Tremblet"
                        },
                        new
                        {
                            Id = 68,
                            Email = "GayeSillars@gmail.com",
                            FullName = "Gaye Sillars"
                        },
                        new
                        {
                            Id = 69,
                            Email = "PieterCurphey@gmail.com",
                            FullName = "Pieter Curphey"
                        },
                        new
                        {
                            Id = 70,
                            Email = "Ewen-MacDearmont@gmail.com",
                            FullName = "Ewen MacDearmont"
                        },
                        new
                        {
                            Id = 71,
                            Email = "ignonPennell@gmail.com",
                            FullName = "Mignon Pennell"
                        },
                        new
                        {
                            Id = 72,
                            Email = "AlanoGeorgot@gmail.com",
                            FullName = "Alano Georgot"
                        },
                        new
                        {
                            Id = 73,
                            Email = "Alleyouch@gmail.com",
                            FullName = "Alley Couch"
                        },
                        new
                        {
                            Id = 74,
                            Email = "LiamOffner@gmail.com",
                            FullName = "Liam Offner"
                        },
                        new
                        {
                            Id = 75,
                            Email = "ElbertinaKleinsinger@gmail.com",
                            FullName = "Elbertina Kleinsinger"
                        },
                        new
                        {
                            Id = 76,
                            Email = "ElbtinaKlsinger@gmail.com",
                            FullName = "Elbtina Klsinger"
                        },
                        new
                        {
                            Id = 77,
                            Email = "NoreanSharpless@gmail.com",
                            FullName = "Norean Sharpless"
                        },
                        new
                        {
                            Id = 78,
                            Email = "VincentsBould@gmail.com",
                            FullName = "Vincents Bould"
                        },
                        new
                        {
                            Id = 79,
                            Email = "ParkerMcGeorge@gmail.com",
                            FullName = "Parker McGeorge"
                        },
                        new
                        {
                            Id = 80,
                            Email = "GregoriusMay@gmail.com",
                            FullName = "Gregorius May"
                        },
                        new
                        {
                            Id = 81,
                            Email = "BevWrigglesworth@gmail.com",
                            FullName = "Bev Wrigglesworth"
                        },
                        new
                        {
                            Id = 82,
                            Email = "CourtneyGawkes@gmail.com",
                            FullName = "Courtney Gawkes"
                        },
                        new
                        {
                            Id = 83,
                            Email = "CourtneyMatiasek@gmail.com",
                            FullName = "Courtney Matiasek"
                        },
                        new
                        {
                            Id = 84,
                            Email = "CoriGunda@gmail.com",
                            FullName = "Corine Gunda"
                        },
                        new
                        {
                            Id = 85,
                            Email = "MandyScoggin@gmail.com",
                            FullName = "Mandy Scoggin"
                        },
                        new
                        {
                            Id = 86,
                            Email = "JuanGorry@gmail.com",
                            FullName = "Juane Gorrynsen"
                        },
                        new
                        {
                            Id = 87,
                            Email = "RandieCridge@gmail.com",
                            FullName = "Randie Cridgeno"
                        },
                        new
                        {
                            Id = 88,
                            Email = "CourtnayDevoy@gmail.com",
                            FullName = "Courtnay Devoy"
                        },
                        new
                        {
                            Id = 89,
                            Email = "HavenSeaton@gmail.com",
                            FullName = "Haven Seaton"
                        },
                        new
                        {
                            Id = 90,
                            Email = "NicolaiSeaborn@gmail.com",
                            FullName = "Nicolai Seaborn"
                        },
                        new
                        {
                            Id = 91,
                            Email = "MonaCrose@gmail.com",
                            FullName = "Mona Crose"
                        },
                        new
                        {
                            Id = 92,
                            Email = "AlysonJankowski@gmail.com",
                            FullName = "Alyson Jankowski"
                        },
                        new
                        {
                            Id = 93,
                            Email = "JeraleeTue@gmail.com",
                            FullName = "Jeralee Tue"
                        },
                        new
                        {
                            Id = 94,
                            Email = "LonnyCarnachen@gmail.com",
                            FullName = "Lonny Carnachen"
                        },
                        new
                        {
                            Id = 95,
                            Email = "KoraNichol@gmail.com",
                            FullName = "Kora Nichol"
                        },
                        new
                        {
                            Id = 96,
                            Email = "KermyBertot@gmail.com",
                            FullName = "Kermy Bertot"
                        },
                        new
                        {
                            Id = 97,
                            Email = "StanislausBaggallay@gmail.com",
                            FullName = "Stanislaus Baggallay"
                        },
                        new
                        {
                            Id = 98,
                            Email = "DannySimoneau@gmail.com",
                            FullName = "Danny Simoneau"
                        },
                        new
                        {
                            Id = 99,
                            Email = "RubinMeaddowcroft@gmail.com",
                            FullName = "Rubin Meaddowcroft"
                        },
                        new
                        {
                            Id = 100,
                            Email = "MarshaCridge@gmail.com",
                            FullName = "Marsha Cridge"
                        },
                        new
                        {
                            Id = 101,
                            Email = "ElyshaMaydwell@gmail.com",
                            FullName = "Elysha Maydwell"
                        },
                        new
                        {
                            Id = 102,
                            Email = "Cridge123@gmail.com",
                            FullName = "Cridge1232"
                        },
                        new
                        {
                            Id = 103,
                            Email = "MarshaC3456@gmail.com",
                            FullName = "Marsha2345"
                        },
                        new
                        {
                            Id = 104,
                            Email = "Mardge123@gmail.com",
                            FullName = "Marde123"
                        },
                        new
                        {
                            Id = 105,
                            Email = "CridgeSe232@gmail.com",
                            FullName = "CdSe232"
                        },
                        new
                        {
                            Id = 106,
                            Email = "Alexander23@gmail.com",
                            FullName = "Axaner23"
                        },
                        new
                        {
                            Id = 107,
                            Email = "Janka123@gmail.com",
                            FullName = "Janka23"
                        },
                        new
                        {
                            Id = 108,
                            Email = "Saxon34@gmail.com",
                            FullName = "S"
                        },
                        new
                        {
                            Id = 109,
                            Email = "Lob@gmail.com",
                            FullName = "Lob"
                        },
                        new
                        {
                            Id = 110,
                            Email = "Ge@gmail.com",
                            FullName = "Ge"
                        });
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pilots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 40,
                            FirstName = "Alexander",
                            LastName = "Jubb",
                            Rating = 3.2999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Age = 54,
                            FirstName = "Cullan",
                            LastName = "Geram",
                            Rating = 1.5
                        },
                        new
                        {
                            Id = 3,
                            Age = 38,
                            FirstName = "Germana",
                            LastName = "Emburey",
                            Rating = 9.1999999999999993
                        },
                        new
                        {
                            Id = 4,
                            Age = 48,
                            FirstName = "Janka",
                            LastName = "Loblie",
                            Rating = 7.5
                        },
                        new
                        {
                            Id = 5,
                            Age = 54,
                            FirstName = "Krystal",
                            LastName = "Cuckson",
                            Rating = 9.0
                        },
                        new
                        {
                            Id = 6,
                            Age = 42,
                            FirstName = "Susy",
                            LastName = "Borrel",
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 7,
                            Age = 43,
                            FirstName = "Saxon",
                            LastName = "Veldman",
                            Rating = 3.2000000000000002
                        },
                        new
                        {
                            Id = 8,
                            Age = 29,
                            FirstName = "Lenore",
                            LastName = "Romera",
                            Rating = 6.9000000000000004
                        },
                        new
                        {
                            Id = 9,
                            Age = 60,
                            FirstName = "Enrichetta",
                            LastName = "Jeremiah",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 10,
                            Age = 24,
                            FirstName = "Delaney",
                            LastName = "Stove",
                            Rating = 6.9000000000000004
                        },
                        new
                        {
                            Id = 11,
                            Age = 25,
                            FirstName = "Ilaire",
                            LastName = "Tomaszewicz",
                            Rating = 7.7999999999999998
                        },
                        new
                        {
                            Id = 12,
                            Age = 36,
                            FirstName = "Genna",
                            LastName = "Jaquet",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 13,
                            Age = 34,
                            FirstName = "Carlotta",
                            LastName = "Dykas",
                            Rating = 6.4000000000000004
                        },
                        new
                        {
                            Id = 14,
                            Age = 57,
                            FirstName = "Viki",
                            LastName = "Oneal",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 15,
                            Age = 43,
                            FirstName = "Anthe",
                            LastName = "Larne",
                            Rating = 7.0999999999999996
                        },
                        new
                        {
                            Id = 16,
                            Age = 45,
                            FirstName = "Philip",
                            LastName = "Penwarden",
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 17,
                            Age = 38,
                            FirstName = "Cristi",
                            LastName = "Ravenshear",
                            Rating = 1.3999999999999999
                        },
                        new
                        {
                            Id = 18,
                            Age = 44,
                            FirstName = "Louie",
                            LastName = "Vogel",
                            Rating = 7.4000000000000004
                        },
                        new
                        {
                            Id = 19,
                            Age = 30,
                            FirstName = "Roddie",
                            LastName = "Gribben",
                            Rating = 8.0
                        },
                        new
                        {
                            Id = 20,
                            Age = 45,
                            FirstName = "Boyce",
                            LastName = "Briddock",
                            Rating = 6.7000000000000002
                        },
                        new
                        {
                            Id = 21,
                            Age = 29,
                            FirstName = "Heidie",
                            LastName = "Blacksell",
                            Rating = 3.1000000000000001
                        },
                        new
                        {
                            Id = 22,
                            Age = 22,
                            FirstName = "Lexie",
                            LastName = "Salasar",
                            Rating = 9.5
                        },
                        new
                        {
                            Id = 23,
                            Age = 46,
                            FirstName = "Harmony",
                            LastName = "Beincken",
                            Rating = 2.2000000000000002
                        },
                        new
                        {
                            Id = 24,
                            Age = 42,
                            FirstName = "Dick",
                            LastName = "Eton",
                            Rating = 8.8000000000000007
                        },
                        new
                        {
                            Id = 25,
                            Age = 54,
                            FirstName = "Philis",
                            LastName = "Treswell",
                            Rating = 6.7999999999999998
                        },
                        new
                        {
                            Id = 26,
                            Age = 55,
                            FirstName = "Crosby",
                            LastName = "Godlee",
                            Rating = 9.5999999999999996
                        },
                        new
                        {
                            Id = 27,
                            Age = 44,
                            FirstName = "Gerhard",
                            LastName = "Alderson",
                            Rating = 7.2000000000000002
                        },
                        new
                        {
                            Id = 28,
                            Age = 24,
                            FirstName = "Dominga",
                            LastName = "Cavy",
                            Rating = 3.6000000000000001
                        },
                        new
                        {
                            Id = 29,
                            Age = 28,
                            FirstName = "Judye",
                            LastName = "Albrooke",
                            Rating = 3.1000000000000001
                        },
                        new
                        {
                            Id = 30,
                            Age = 47,
                            FirstName = "Felice",
                            LastName = "Bartol",
                            Rating = 2.1000000000000001
                        },
                        new
                        {
                            Id = 31,
                            Age = 36,
                            FirstName = "Adolpho",
                            LastName = "Wainscot",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 32,
                            Age = 49,
                            FirstName = "Aurilia",
                            LastName = "McCready",
                            Rating = 1.3999999999999999
                        },
                        new
                        {
                            Id = 33,
                            Age = 37,
                            FirstName = "Neill",
                            LastName = "Woof",
                            Rating = 8.5
                        },
                        new
                        {
                            Id = 34,
                            Age = 60,
                            FirstName = "Rab",
                            LastName = "McDarmid",
                            Rating = 2.3999999999999999
                        },
                        new
                        {
                            Id = 35,
                            Age = 46,
                            FirstName = "Ardith",
                            LastName = "Kienlein",
                            Rating = 9.6999999999999993
                        },
                        new
                        {
                            Id = 36,
                            Age = 56,
                            FirstName = "Berenice",
                            LastName = "Liddiatt",
                            Rating = 1.6000000000000001
                        },
                        new
                        {
                            Id = 37,
                            Age = 59,
                            FirstName = "Ailina",
                            LastName = "Sebyer",
                            Rating = 8.6999999999999993
                        },
                        new
                        {
                            Id = 38,
                            Age = 22,
                            FirstName = "Jaynell",
                            LastName = "Kidson",
                            Rating = 6.2000000000000002
                        },
                        new
                        {
                            Id = 39,
                            Age = 38,
                            FirstName = "Carina",
                            LastName = "Vanyatin",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 40,
                            Age = 57,
                            FirstName = "Edna",
                            LastName = "Heatley",
                            Rating = 7.5
                        },
                        new
                        {
                            Id = 41,
                            Age = 46,
                            FirstName = "Hally",
                            LastName = "Barthelmes",
                            Rating = 8.9000000000000004
                        },
                        new
                        {
                            Id = 42,
                            Age = 40,
                            FirstName = "Leanna",
                            LastName = "Olensby",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 43,
                            Age = 23,
                            FirstName = "Dell",
                            LastName = "Willoughey",
                            Rating = 6.2999999999999998
                        },
                        new
                        {
                            Id = 44,
                            Age = 33,
                            FirstName = "Guinevere",
                            LastName = "Gras",
                            Rating = 6.2999999999999998
                        },
                        new
                        {
                            Id = 45,
                            Age = 21,
                            FirstName = "Jerrie",
                            LastName = "Myles",
                            Rating = 1.8
                        },
                        new
                        {
                            Id = 46,
                            Age = 52,
                            FirstName = "Francoise",
                            LastName = "Cusack",
                            Rating = 1.1000000000000001
                        },
                        new
                        {
                            Id = 47,
                            Age = 41,
                            FirstName = "Happy",
                            LastName = "Bezant",
                            Rating = 8.3000000000000007
                        },
                        new
                        {
                            Id = 48,
                            Age = 58,
                            FirstName = "Kingsly",
                            LastName = "Ianiello",
                            Rating = 7.0999999999999996
                        },
                        new
                        {
                            Id = 49,
                            Age = 28,
                            FirstName = "Leonhard",
                            LastName = "Tukely",
                            Rating = 5.0999999999999996
                        },
                        new
                        {
                            Id = 50,
                            Age = 21,
                            FirstName = "Joe",
                            LastName = "Waine",
                            Rating = 4.4000000000000004
                        });
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.PilotAircraft", b =>
                {
                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.HasKey("PilotId", "AircraftId");

                    b.HasIndex("AircraftId");

                    b.ToTable("PilotAircrafts");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.Aircraft", b =>
                {
                    b.HasOne("Airport.DAL.EF.Entities.AircraftType", "AircraftType")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AircraftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftType");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.FlightDestination", b =>
                {
                    b.HasOne("Airport.DAL.EF.Entities.Aircraft", "Aircraft")
                        .WithMany("FlightDestinations")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airport.DAL.EF.Entities.AirportEntity", "Airport")
                        .WithMany("FlightDestinations")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airport.DAL.EF.Entities.Passenger", "Passenger")
                        .WithMany("FlightDestinations")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airport");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.PilotAircraft", b =>
                {
                    b.HasOne("Airport.DAL.EF.Entities.Aircraft", "Aircraft")
                        .WithMany("PilotAircrafts")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Airport.DAL.EF.Entities.Pilot", "Pilot")
                        .WithMany("PilotAircrafts")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.Aircraft", b =>
                {
                    b.Navigation("FlightDestinations");

                    b.Navigation("PilotAircrafts");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.AircraftType", b =>
                {
                    b.Navigation("Aircrafts");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.AirportEntity", b =>
                {
                    b.Navigation("FlightDestinations");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.Passenger", b =>
                {
                    b.Navigation("FlightDestinations");
                });

            modelBuilder.Entity("Airport.DAL.EF.Entities.Pilot", b =>
                {
                    b.Navigation("PilotAircrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
